ARG BASE_IMAGE=docker.io/agners/archlinuxarm@sha256:cd2eb76b34be8dd6ae52ba4e3531228a3a6f754f82d05fadbb30fb25036d1e05
FROM ${BASE_IMAGE}

COPY packages.txt /tmp/meowarch-packages.txt
RUN pacman -Syu --noconfirm --needed $(grep -vE '^[[:space:]]*(#|$)' /tmp/meowarch-packages.txt)

RUN useradd --create-home --uid 1000 --shell /bin/bash meowarch \
    && printf 'meowarch ALL=(ALL) NOPASSWD: ALL\n' >/etc/sudoers.d/meowarch \
    && chmod 0440 /etc/sudoers.d/meowarch

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
WORKDIR /workspace
